// GENERATED by training/gpu_email/gen_keywords.py from training/gpu_email/features.py.
// Do not edit by hand; both featurizers must share these tables byte-for-byte.

export const KW_WROTE = ["wrote", "écrit", "ecrit", "schrieb", "escribió", "escribio", "escreveu", "skrev", "scritto", "schreef", "napisał", "napsal", "写道", "書きました"] as const;

export const KW_ORIGINAL = ["original message", "ursprüngliche nachricht", "message d'origine", "mensaje original", "messaggio originale", "oorspronkelijk bericht", "原始邮件", "元のメッセージ", "original appointment"] as const;

export const KW_FORWARD = ["forwarded message", "begin forwarded", "weitergeleitete nachricht", "message transféré", "mensaje reenviado", "messaggio inoltrato", "doorgestuurd bericht", "转发", "転送", "fwd:"] as const;

export const KW_MOBILE = ["sent from my", "sent from a", "envoyé de mon", "von meinem", "enviado desde mi", "inviato da", "verzonden vanaf", "から送信", "get outlook for", "sent via", "sent with", "sent from mail", "sent from outlook"] as const;

export const KW_HEADER = ["from:", "sent:", "to:", "subject:", "date:", "cc:", "reply-to:", "von:", "gesendet:", "an:", "betreff:", "datum:", "de :", "de:", "envoyé :", "envoyé:", "à :", "à:", "objet :", "objet:", "para:", "enviado el:", "enviado:", "asunto:", "fecha:", "da:", "inviato:", "a:", "oggetto:", "差出人:", "送信日時:", "宛先:", "件名:", "发件人:", "发送时间:", "收件人:", "主题:", "差出人：", "宛先：", "件名：", "发件人：", "收件人：", "主题："] as const;

export const KW_DISCLAIMER = ["confidential", "intended recipient", "disclaimer", "privileged", "unauthorized", "unauthorised", "vertraulich", "confidentiel", "confidencial", "unsubscribe", "mailing list", "this email", "this e-mail", "this message", "diese e-mail", "ce message", "este mensaje", "please consider the environment", "virus", "legally", "liability", "the sender", "notify", "registered in", "registered office"] as const;

export const KW_CONTACT_WORDS = ["tel", "phone", "mobile", "mob", "cell", "fax", "office", "direct", "e-mail", "email", "mail", "web", "www", "skype", "linkedin", "twitter", "whatsapp", "téléphone", "telefon", "teléfono", "telefono", "portable", "handy", "móvil", "movil", "手机", "電話", "电话", "tél", "ph", "m", "t", "p", "f", "e", "w", "d", "o", "c"] as const;

export const KW_CLOSING_WORDS = ["regards", "thanks", "cheers", "best", "sincerely", "cordialement", "grüßen", "grüße", "gruß", "saludos", "atentamente", "merci", "danke", "gracias", "thx", "ty", "kind", "warm", "warmly", "yours", "truly", "care", "soon", "bye", "ciao", "wishes", "cordiali", "cumprimentos", "obrigado", "hälsningar", "groeten", "abrazo", "bien", "amicalement", "bises", "liebe", "viele", "beste", "mfg", "vg", "lg", "br", "rgds", "thank", "appreciate", "talk", "speak", "よろしく", "谢谢", "敬上", "祝好", "敬具"] as const;

export const KW_GREETING_WORDS = ["hi", "hello", "hey", "dear", "morning", "afternoon", "evening", "bonjour", "hallo", "hola", "salut", "guten", "geehrte", "geehrter", "liebe", "lieber", "こんにちは", "你好", "您好", "greetings", "team", "all", "folks", "everyone", "everybody", "hiya", "yo", "buongiorno", "olá", "ola", "hej", "hoi", "estimado", "estimada", "cher", "chère", "sir", "madam", "mr", "ms", "mrs", "dr", "herr", "frau", "monsieur", "madame", "señor", "señora"] as const;

export const KW_DATE_WORDS = ["jan", "feb", "mar", "apr", "may", "jun", "jul", "aug", "sep", "sept", "oct", "nov", "dec", "january", "february", "march", "april", "june", "july", "august", "september", "october", "november", "december", "janv", "févr", "fév", "mars", "avr", "avril", "mai", "juin", "juil", "juillet", "août", "déc", "janvier", "février", "octobre", "novembre", "décembre", "septembre", "januar", "februar", "märz", "juni", "juli", "oktober", "dezember", "ene", "abr", "ago", "dic", "enero", "febrero", "marzo", "mayo", "junio", "julio", "agosto", "septiembre", "octubre", "noviembre", "diciembre", "mon", "tue", "wed", "thu", "fri", "sat", "sun", "monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday", "lundi", "mardi", "mercredi", "jeudi", "vendredi", "samedi", "dimanche", "montag", "dienstag", "mittwoch", "donnerstag", "freitag", "samstag", "sonntag", "lunes", "martes", "miércoles", "jueves", "viernes", "sábado", "domingo", "am", "pm", "uhr", "at", "um", "às", "kl", "年", "月", "日", "午前", "午後"] as const;

export const KW_CLOSING_PHRASES = ["thank you", "take care", "talk soon", "speak soon", "all the best", "best wishes", "mit freundlichen", "bien à vous", "un saludo", "kind regards", "warm regards", "many thanks"] as const;

export const KW_GREETING_PHRASES = ["good morning", "good afternoon", "good evening", "sehr geehrte", "お世話になっております", "dear all", "hi all", "hi there", "hello there"] as const;

export const EDGES_LINE_IDX = [0, 1, 2, 3, 4, 7, 11, 19] as const;

export const EDGES_LINE_LEN = [0, 3, 10, 20, 40, 60, 80, 100] as const;

export const EDGES_WORD_COUNT = [0, 1, 2, 3, 4, 6, 9, 14] as const;

export const EDGES_DIGITS = [0, 2, 5, 8, 12] as const;

export const EDGES_SINCE_ATTRIB = [0, 1, 2, 3, 5, 9] as const;

export const EDGES_PARA = [0, 1, 2, 3, 5] as const;

export const EDGES_PARA_POS = [0, 1, 2, 3, 4, 7] as const;

export const EDGES_UNTIL_QUOTEISH = [1, 2, 3, 4, 6, 10] as const;

export const EDGES_HEADER_RUN = [0, 1, 2, 3] as const;

export const LINE_KINDS = ["reply", "attribution", "quote", "signature", "disclaimer", "forward_header", "greeting", "closing"] as const;

export const FIELDS = ["NAME", "TITLE", "COMPANY", "PHONE", "EMAIL", "URL", "ADDRESS"] as const;

export const BIO_LABELS = ["O", "B-NAME", "I-NAME", "B-TITLE", "I-TITLE", "B-COMPANY", "I-COMPANY", "B-PHONE", "I-PHONE", "B-EMAIL", "I-EMAIL", "B-URL", "I-URL", "B-ADDRESS", "I-ADDRESS"] as const;

export const SLOTS = [["word", 1024], ["shape", 8], ["len", 16], ["cls", 5], ["suffix", 512], ["pos_in_line", 9], ["line_flags", 8], ["line_from_top", 9], ["line_from_bottom", 9], ["line_len", 9], ["first_word", 256], ["first_shape", 9], ["last_word", 256], ["last_char", 9], ["content_flags", 8], ["word_count", 9], ["title_frac", 6], ["digit_count", 6], ["neighbours", 16], ["kw_wrote", 2], ["kw_original", 2], ["kw_forward", 2], ["kw_mobile", 2], ["kw_header", 2], ["kw_disclaimer", 2], ["kw_contact", 2], ["kw_closing", 2], ["kw_greeting", 2], ["kw_date", 2], ["ctx_above", 16], ["since_attrib", 8], ["since_blank", 7], ["until_blank", 7], ["until_quoteish", 8], ["header_run", 5], ["para_from_top", 6], ["para_from_bottom", 6]] as const;

export const SLOT_BASE = [0, 1024, 1032, 1048, 1053, 1565, 1574, 1582, 1591, 1600, 1609, 1865, 1874, 2130, 2139, 2147, 2156, 2162, 2168, 2184, 2186, 2188, 2190, 2192, 2194, 2196, 2198, 2200, 2202, 2204, 2220, 2228, 2235, 2242, 2250, 2255, 2261] as const;

export const NUM_SLOTS = 37;

export const NUM_ROWS = 2267;

export const WORD_BUCKETS = 1024;

export const SUFFIX_BUCKETS = 512;

export const FIRST_WORD_BUCKETS = 256;

export const LAST_WORD_BUCKETS = 256;
