"""Natural-language value phrases -> typed value "kind:value".

Kinds understood by the compiler (src/compile.ts):
  sz   size word on a scale (xs sm md lg xl 2xl 3xl 4xl); per-family mapping
  kw   keyword utility value (center, between, hidden, uppercase ...)
  col  a colour, optionally with shade (gray-500, white, transparent)
  mod  a colour shade modifier (light -> 300, dark -> 700, ...)
  wt   font weight
  rad  radius keyword (full, none)
  num  a number word (four -> 4)
  frac a fraction (half -> 1/2)
  int  intensifier (very -> +1, slightly -> -1)
  spec special multi-class values handled by the compiler (center, fullscreen ...)
"""

from __future__ import annotations

VALUES: dict[str, list[str]] = {
    # sizes
    "sz:xs": ["xs", "extra small", "tiny", "teeny", "minimal", "hairline", "faint", "xsmall"],
    "sz:sm": ["sm", "small", "subtle", "slight", "little", "light touch", "gentle", "soft", "smaller", "narrow", "compact", "thin", "low", "short"],
    "sz:md": ["md", "medium", "regular", "moderate", "normal", "default", "standard", "mid", "middle", "average", "base"],
    "sz:lg": ["lg", "large", "big", "larger", "bigger", "generous", "wide", "roomy", "thick", "strong", "heavy", "deep", "prominent", "tall", "high", "spacious"],
    "sz:xl": ["xl", "extra large", "huge", "very large", "xlarge", "x large", "extra big", "giant", "massive", "oversized", "extra wide", "extra thick"],
    "sz:2xl": ["2xl", "2 xl", "xxl", "double extra large", "enormous", "gigantic", "jumbo", "very huge"],
    "sz:3xl": ["3xl", "3 xl", "xxxl", "triple extra large", "colossal", "hero", "display"],
    "sz:4xl": ["4xl", "4 xl", "quadruple extra large"],
    "sz:5xl": ["5xl", "5 xl"],
    "sz:6xl": ["6xl", "6 xl"],
    "sz:7xl": ["7xl", "7 xl"],
    "sz:8xl": ["8xl"],
    "sz:9xl": ["9xl"],
    "sz:none": ["none", "no", "zero", "nothing", "removed", "off", "without", "flat", "0"],
    "sz:full": ["full", "fully", "complete", "completely", "entire", "whole", "100%", "100 percent", "max", "maximum", "all the way"],
    # intensifiers
    "int:1": ["very", "extra", "super", "really", "quite", "more", "much", "heavily", "strongly", "pretty", "ultra", "mega", "highly"],
    "int:-1": ["slightly", "a bit", "a little", "somewhat", "less", "barely", "just a bit", "a touch", "mildly", "lightly", "kinda", "kind of", "sort of", "softly"],
    # weights
    "wt:thin": ["thin weight", "hairline weight", "thinnest", "weight 100", "100 weight"],
    "wt:extralight": ["extralight", "extra light", "ultralight", "ultra light", "weight 200"],
    "wt:light": ["light weight", "lightweight", "weight 300", "lighter weight", "light font"],
    "wt:normal": ["normal weight", "regular weight", "weight 400", "not bold", "unbold", "book weight"],
    "wt:medium": ["medium weight", "weight 500", "medium bold", "semi bold ish", "medium font"],
    "wt:semibold": ["semibold", "semi bold", "semi-bold", "demibold", "demi bold", "weight 600", "fairly bold", "slightly bold"],
    "wt:bold": ["bold", "bolded", "boldface", "strong text", "emphasized", "weight 700", "heavy weight", "bolder", "in bold", "bold text", "bold font"],
    "wt:extrabold": ["extrabold", "extra bold", "ultrabold", "ultra bold", "very bold", "weight 800", "super bold", "really bold"],
    "wt:black": ["black weight", "heaviest", "weight 900", "blackest", "heaviest weight", "extra heavy", "black font"],
    # colour modifiers
    "mod:100": ["very light", "very pale", "faint", "lightest", "palest", "barely tinted", "whisper", "pastel", "washed out", "extra light"],
    "mod:200": ["lighter", "pale", "tint", "tinted", "airy"],
    "mod:300": ["light", "soft", "gentle", "mild"],
    "mod:400": ["muted", "dim", "dull", "desaturated", "subdued", "dusty", "quiet"],
    "mod:500": ["bright", "vivid", "plain", "pure", "regular", "medium", "standard", "default", "normal", "saturated"],
    "mod:600": ["strong", "rich", "bold", "vibrant", "deep", "intense", "punchy", "saturated deep"],
    "mod:700": ["dark", "darker", "shaded", "dim dark", "burnt"],
    "mod:800": ["very dark", "darkest", "extra dark", "midnight", "charcoal"],
    "mod:900": ["deepest", "almost black", "near black", "ink", "ultra dark", "blackish"],
    "mod:950": ["pitch dark", "nearly black", "deepest dark", "black-ish"],
    # special colours
    "col:white": ["white", "#fff", "#ffffff", "pure white", "snow"],
    "col:black": ["black", "#000", "#000000", "pure black", "jet black"],
    "col:transparent": ["transparent", "see through", "clear", "no color", "no colour", "colorless", "invisible color"],
    "col:current": ["current color", "currentcolor", "current", "inherit color", "same color as text"],
    "col:gray-500": ["muted", "grayish", "greyish", "dimmed", "secondary", "subdued", "quiet"],
    "col:gray-400": ["placeholder", "hint", "faded", "ghost", "disabled looking", "tertiary"],
    "col:gray-900": ["near black", "almost black", "ink", "dark text", "headline"],
    "col:gray-50": ["off white", "off-white", "almost white", "nearly white", "eggshell", "light surface"],
    "col:gray-100": ["very light gray", "very light grey", "whitish", "light surface gray", "smoke"],
    "col:gray-200": ["light gray", "light grey", "silver", "pale gray", "pale grey", "subtle gray", "subtle grey"],
    "col:gray-800": ["dark gray", "dark grey", "charcoal", "graphite", "slate dark"],
    "col:red-500": ["danger", "error", "destructive", "alert red", "crimson"],
    "col:red-600": ["error dark", "danger dark"],
    "col:green-500": ["success", "ok", "positive", "valid", "go", "grass"],
    "col:green-600": ["success dark", "forest"],
    "col:yellow-400": ["warning", "caution", "gold", "golden", "sunny"],
    "col:amber-500": ["amber warning", "honey", "warn"],
    "col:blue-500": ["info", "informational", "azure", "primary", "brand", "link blue", "accent"],
    "col:blue-600": ["royal blue", "primary dark", "brand dark"],
    "col:sky-500": ["sky", "light blue sky", "cerulean"],
    "col:indigo-500": ["indigo blue", "periwinkle"],
    "col:purple-500": ["violet purple", "grape"],
    "col:pink-500": ["hot pink", "magenta pink", "bubblegum"],
    "col:rose-500": ["rosy", "rose red"],
    "col:orange-500": ["tangerine", "carrot"],
    "col:teal-500": ["aqua teal", "sea green"],
    "col:emerald-500": ["emerald green", "jade"],
    "col:lime-500": ["lime green", "chartreuse"],
    "col:cyan-500": ["cyan blue", "turquoise"],
    "col:slate-500": ["slate gray", "slate grey", "blue gray", "blue grey", "steel"],
    "col:zinc-500": ["zinc gray", "zinc grey", "cool gray", "cool grey"],
    "col:neutral-500": ["neutral gray", "neutral grey", "true gray", "true grey"],
    "col:stone-500": ["stone gray", "stone grey", "warm gray", "warm grey", "greige"],
    "col:fuchsia-500": ["fuchsia pink"],
    "col:violet-500": ["lavender", "lilac"],
    "col:amber-100": ["cream", "creamy", "ivory", "beige", "sand"],
    "col:red-50": ["blush", "very pale red"],
    "col:blue-50": ["ice", "icy blue", "very pale blue"],
    "col:green-50": ["mint", "minty"],
    "col:yellow-100": ["butter", "lemon"],
    # radii keywords
    "rad:full": ["pill", "pill shaped", "pill-shaped", "circle", "circular", "round", "fully rounded", "completely rounded", "capsule", "rounded full", "oval", "totally round", "round shape", "stadium"],
    "rad:none": ["square corners", "sharp corners", "sharp", "squared", "not rounded", "no rounding", "unrounded", "hard corners", "square edges", "90 degree corners"],
    # numbers
    "num:0": ["zero", "none", "no"],
    "num:1": ["one", "single", "a single", "1x"],
    "num:2": ["two", "double", "a couple", "2x", "pair"],
    "num:3": ["three", "triple", "3x"],
    "num:4": ["four", "quadruple", "4x"],
    "num:5": ["five"],
    "num:6": ["six", "half dozen"],
    "num:7": ["seven"],
    "num:8": ["eight"],
    "num:9": ["nine"],
    "num:10": ["ten"],
    "num:11": ["eleven"],
    "num:12": ["twelve", "dozen", "a dozen"],
    "num:16": ["sixteen"],
    "num:20": ["twenty"],
    "num:24": ["twenty four", "twenty-four"],
    "num:25": ["twenty five", "a quarter", "twenty-five"],
    "num:32": ["thirty two", "thirty-two"],
    "num:40": ["forty"],
    "num:48": ["forty eight", "forty-eight"],
    "num:50": ["fifty", "half"],
    "num:60": ["sixty"],
    "num:64": ["sixty four", "sixty-four"],
    "num:75": ["seventy five", "three quarters", "seventy-five"],
    "num:80": ["eighty"],
    "num:90": ["ninety"],
    "num:96": ["ninety six", "ninety-six"],
    "num:100": ["hundred", "one hundred", "a hundred"],
    "frac:1/2": ["half", "one half", "1/2", "50%", "fifty percent", "halfway", "half of"],
    "frac:1/3": ["third", "one third", "a third", "1/3", "33%", "thirty three percent"],
    "frac:2/3": ["two thirds", "2/3", "66%", "67%", "two-thirds"],
    "frac:1/4": ["quarter", "one quarter", "a quarter", "1/4", "25%", "fourth", "one fourth"],
    "frac:3/4": ["three quarters", "3/4", "75%", "three fourths", "three-quarters"],
    "frac:1/5": ["fifth", "one fifth", "1/5", "20%"],
    "frac:2/5": ["two fifths", "2/5", "40%"],
    "frac:3/5": ["three fifths", "3/5", "60%"],
    "frac:4/5": ["four fifths", "4/5", "80%"],
    "frac:1/6": ["sixth", "one sixth", "1/6"],
    "frac:5/6": ["five sixths", "5/6"],
    "frac:1/12": ["twelfth", "one twelfth", "1/12"],
    # keywords
    "kw:screen": ["screen", "viewport", "screen height", "screen width", "full screen", "fullscreen", "whole screen", "viewport height", "viewport width", "full viewport"],
    "kw:auto": ["auto", "automatic", "automatically", "natural", "intrinsic", "as needed", "content sized", "content-sized", "sized to content"],
    "kw:fit": ["fit", "fit content", "fit-content", "shrink to fit", "hug", "hug content", "hugging", "hugs content", "as wide as its content"],
    "kw:min": ["min content", "min-content", "minimum content", "as narrow as possible"],
    "kw:max": ["max content", "max-content", "as wide as possible"],
    "kw:prose": ["prose", "readable", "reading width", "readable width", "prose width", "65 characters", "65ch", "article width"],
    "kw:center": ["center", "centered", "centred", "centre", "in the center", "in the middle", "middle", "centrally", "center aligned", "centre aligned", "at the center", "centered up"],
    "kw:start": ["start", "at the start", "flex start", "flex-start", "top aligned", "to the start", "aligned to start", "leading"],
    "kw:end": ["end", "at the end", "flex end", "flex-end", "bottom aligned", "to the end", "aligned to end", "trailing"],
    "kw:left": ["left", "left aligned", "to the left", "on the left", "left justified", "flush left", "ragged right"],
    "kw:right": ["right", "right aligned", "to the right", "on the right", "right justified", "flush right", "ragged left"],
    "kw:justify": ["justified", "justify", "fully justified", "even edges", "block justified"],
    "kw:between": ["between", "space between", "space-between", "spread out", "spaced out", "pushed apart", "at opposite ends", "evenly with edges", "spaced between", "opposite ends"],
    "kw:around": ["around", "space around", "space-around", "spaced around", "space on both sides"],
    "kw:evenly": ["evenly", "space evenly", "space-evenly", "evenly spaced", "equal spacing", "equal gaps", "equally spaced"],
    "kw:stretch": ["stretch", "stretched", "stretched to fill", "fill height", "stretch to fill", "full height items", "filling"],
    "kw:baseline": ["baseline", "on the baseline", "baseline aligned", "text baseline"],
    "kw:top": ["top", "at the top", "to the top", "upper", "top edge"],
    "kw:bottom": ["bottom", "at the bottom", "to the bottom", "lower", "bottom edge"],
    "kw:row": ["row", "horizontal", "horizontally", "side by side", "in a row", "left to right", "inline row", "across", "in a line", "next to each other"],
    "kw:row-reverse": ["row reverse", "reversed row", "reverse row", "right to left", "row reversed"],
    "kw:col": ["column", "col", "vertical", "vertically", "stacked", "stacked vertically", "top to bottom", "in a column", "one on top of the other", "downward", "up and down", "on top of each other"],
    "kw:col-reverse": ["column reverse", "reversed column", "reverse column", "bottom to top", "col reverse"],
    "kw:wrap": ["wrap", "wraps", "wrapping", "wrapped", "allow wrapping", "multi line", "multiline", "can wrap", "wrap around", "wrap onto multiple lines"],
    "kw:nowrap": ["nowrap", "no wrap", "no-wrap", "single line", "one line", "never wrap", "doesn't wrap", "unwrapped", "don't wrap", "not wrapping", "does not wrap", "on one line"],
    "kw:wrap-reverse": ["wrap reverse", "reverse wrap", "wrap-reverse"],
    "kw:hidden": ["hidden", "hide", "hides", "invisible", "not shown", "not visible", "not displayed", "display none", "gone", "removed from view", "doesn't show", "don't show", "not rendered", "collapsed", "no display", "disappears", "disappear", "never shown"],
    "kw:visible": ["visible", "shown", "show", "shows", "displayed", "appears", "appear", "seen", "revealed", "reveal", "on screen"],
    "kw:block": ["block", "block level", "block-level", "as a block", "full row", "display block"],
    "kw:inline": ["inline", "inline element", "in line", "in text"],
    "kw:inline-block": ["inline block", "inline-block"],
    "kw:inline-flex": ["inline flex", "inline-flex"],
    "kw:inline-grid": ["inline grid", "inline-grid"],
    "kw:contents": ["contents", "display contents"],
    "kw:table": ["table", "as a table"],
    "kw:absolute": ["absolute", "absolutely positioned", "absolutely", "floating", "positioned absolutely", "overlaid", "on top of"],
    "kw:relative": ["relative", "relatively positioned", "positioned relatively", "relative position", "positioning context"],
    "kw:fixed": ["fixed", "fixed position", "fixed to the screen", "fixed to the viewport", "stays in place", "stays put", "pinned to screen", "pinned"],
    "kw:sticky": ["sticky", "stuck", "sticks", "sticks to", "sticky positioned", "stays on scroll", "sticky top"],
    "kw:static": ["static", "static position", "normal flow", "unpositioned"],
    "kw:scroll": ["scrollable", "scrolls", "always scroll", "scrollbar", "with scrollbar", "scrolling enabled", "scroll bars"],
    "kw:overflow-auto": ["auto overflow", "scroll if needed", "scroll when needed", "scroll as needed", "overflow auto", "scrollable when needed", "scrolls when needed", "scrolls if needed", "can scroll"],
    "kw:clip": ["clip", "clipped", "cut off", "clip overflow", "overflow clipped", "cropped", "cropping", "crop", "no overflow", "overflow hidden", "hide overflow", "contained", "clipped overflow", "hides overflow"],
    "kw:overflow-visible": ["overflow visible", "visible overflow", "spill", "spills out", "can overflow", "allowed to overflow", "overflows"],
    "kw:uppercase": ["uppercase", "upper case", "all caps", "caps", "capitals", "capital letters", "upper", "in caps", "all uppercase", "shouting", "all capital"],
    "kw:lowercase": ["lowercase", "lower case", "all lowercase", "small letters", "no caps", "in lowercase"],
    "kw:capitalize": ["capitalize", "capitalise", "capitalized", "capitalised", "title case", "titlecase", "capitalize each word", "capitalise each word", "each word capitalized", "sentence caps", "first letter capitalized"],
    "kw:normal-case": ["normal case", "no transform", "original case", "as typed", "not uppercase", "not capitalized"],
    "kw:italic": ["italic", "italics", "italicized", "italicised", "slanted", "oblique", "in italics", "cursive style", "emphasis italic"],
    "kw:not-italic": ["not italic", "upright", "roman", "no italics", "non italic", "unitalic"],
    "kw:underline": ["underline", "underlined", "with underline", "underscored", "underlining"],
    "kw:no-underline": ["no underline", "not underlined", "without underline", "remove underline", "underline removed", "no decoration", "undecorated", "plain link"],
    "kw:line-through": ["line through", "strikethrough", "strike through", "struck through", "crossed out", "strikeout", "struck out", "strike"],
    "kw:overline": ["overline", "overlined", "line above"],
    "kw:truncate": ["truncate", "truncated", "ellipsis", "with ellipsis", "cut off with ellipsis", "truncate with dots", "elided", "single line ellipsis", "dot dot dot", "trailing ellipsis", "clipped with ellipsis", "ellipsized", "trimmed with ellipsis"],
    "kw:balance": ["balanced", "balance", "balanced wrapping", "text balance", "balanced lines"],
    "kw:pretty": ["pretty", "pretty wrapping", "no orphans", "text pretty", "avoid orphans"],
    "kw:break-words": ["break words", "word break", "break long words", "wrap long words", "break-words", "overflow wrap", "breaks words"],
    "kw:break-all": ["break all", "break anywhere", "break-all", "break every character"],
    "kw:pre": ["preformatted", "pre", "preserve whitespace", "keep whitespace", "whitespace pre", "keep spaces", "preserve spaces"],
    "kw:pre-wrap": ["pre wrap", "pre-wrap", "preserve whitespace and wrap", "keep whitespace and wrap"],
    "kw:pre-line": ["pre line", "pre-line", "preserve newlines", "keep line breaks", "keep newlines"],
    "kw:sans": ["sans", "sans serif", "sans-serif", "system font", "default font", "helvetica", "arial", "inter", "roboto", "system ui"],
    "kw:serif": ["serif", "georgia", "times", "times new roman", "book font", "with serifs"],
    "kw:mono": ["mono", "monospace", "monospaced", "code font", "fixed width font", "fixed-width", "typewriter", "courier", "terminal font", "code style", "like code"],
    "kw:tighter": ["tighter", "very tight", "tightest", "squeezed", "condensed", "cramped"],
    "kw:tight": ["tight", "tightly", "snug", "close together", "compressed", "narrow spacing"],
    "kw:wide": ["wide", "spaced", "spread", "letterspaced", "letter spaced", "airy", "expanded", "loose spacing", "open"],
    "kw:wider": ["wider", "very wide", "spaced out", "extra spaced", "widely spaced"],
    "kw:widest": ["widest", "extremely wide", "maximum spacing", "very spaced out", "super wide"],
    "kw:snug": ["snug", "snug lines"],
    "kw:relaxed": ["relaxed", "relaxed lines", "roomy lines", "comfortable", "generous line height", "spacious lines"],
    "kw:loose": ["loose", "loose lines", "double spaced", "very tall lines", "airy lines", "lots of line spacing", "double spacing"],
    "kw:pointer": ["pointer", "hand", "hand cursor", "clickable", "pointer cursor", "click cursor", "looks clickable", "hand pointer", "finger"],
    "kw:not-allowed": ["not allowed", "not-allowed", "forbidden", "no cursor", "disabled cursor", "blocked cursor", "prohibited", "unavailable cursor"],
    "kw:wait": ["wait", "loading cursor", "hourglass", "busy", "spinner cursor", "waiting"],
    "kw:grab": ["grab", "grabbable", "grab cursor", "draggable", "drag handle", "open hand"],
    "kw:move": ["move", "move cursor", "crosshair move", "movable"],
    "kw:text-cursor": ["text cursor", "i beam", "i-beam", "ibeam", "caret cursor"],
    "kw:default-cursor": ["default cursor", "arrow cursor", "arrow", "normal cursor", "regular cursor"],
    "kw:select-none": ["not selectable", "unselectable", "no text selection", "prevent selection", "can't select", "cannot be selected", "no select", "disable selection", "non selectable", "selection disabled"],
    "kw:select-all": ["select all", "selects all", "select everything", "whole text selected on click", "select all on click"],
    "kw:select-text": ["selectable text", "allow selection", "text selectable", "can be selected"],
    "kw:events-none": ["ignore clicks", "click through", "no pointer events", "pointer events none", "not clickable", "unclickable", "ignores mouse", "passes clicks through", "mouse events off", "no mouse events", "inert"],
    "kw:events-auto": ["pointer events auto", "accepts clicks", "receives clicks", "clickable again", "mouse events on"],
    "kw:cover": ["cover", "covers", "cover fit", "object cover", "fill the box", "cover the area", "cover the box", "cropped to fill", "filling the frame"],
    "kw:contain": ["contain", "contained fit", "object contain", "fit inside", "letterbox", "letterboxed", "fit within", "fits inside", "scaled to fit"],
    "kw:fill": ["fill", "stretched to fill box", "object fill", "distorted to fill"],
    "kw:square": ["square", "1:1", "1 by 1", "one to one", "square ratio", "1/1", "equal sides", "square aspect"],
    "kw:video": ["video", "16:9", "16 by 9", "widescreen", "video ratio", "16/9", "sixteen by nine", "cinematic"],
    "kw:spin": ["spin", "spinning", "spins", "rotating", "rotate continuously", "loader spin", "spinner", "spinning loader", "loading spinner"],
    "kw:ping": ["ping", "pinging", "radar", "pulse ring", "ripple", "sonar"],
    "kw:pulse": ["pulse", "pulsing", "pulsating", "throbbing", "skeleton", "skeleton loading", "shimmer", "breathing", "fading in and out"],
    "kw:bounce": ["bounce", "bouncing", "bounces", "bouncy", "jumping", "hopping"],
    "kw:disc": ["bullets", "bulleted", "disc", "dots", "bullet points", "with bullets", "unordered"],
    "kw:decimal": ["numbered", "numbers", "decimal", "ordered", "numeric list", "with numbers", "1 2 3"],
    "kw:first": ["first", "at the front", "moved to the front", "in front", "before everything", "beginning"],
    "kw:last": ["last", "at the back", "moved to the end", "after everything", "at the very end"],
    "kw:colors": ["colors", "colours", "color changes", "colour changes", "just colors", "only colors", "color transition", "colour transition"],
    "kw:all": ["all", "everything", "all properties", "every property"],
    "kw:opacity": ["opacity only", "just opacity", "fade", "fading", "fades", "fade only"],
    "kw:shadow": ["shadow only", "just the shadow", "shadow transition"],
    "kw:transform": ["transform only", "just transform", "movement", "transforms", "transform transition"],
    "kw:linear": ["linear", "constant speed", "no easing", "even speed", "linearly"],
    "kw:ease-in": ["ease in", "ease-in", "accelerating", "starts slow", "slow start", "speeds up", "accelerate"],
    "kw:ease-out": ["ease out", "ease-out", "decelerating", "ends slow", "slow end", "slows down", "decelerate", "settles"],
    "kw:ease-in-out": ["ease in out", "ease-in-out", "smooth both ways", "slow start and end", "in and out"],
    "kw:fast": ["fast", "quick", "quickly", "snappy", "rapid", "brief", "instant-ish", "short duration", "speedy", "fast transition", "quick transition"],
    "kw:slow": ["slow", "slowly", "leisurely", "long", "lengthy", "gradual", "gradually", "long duration", "slow transition", "sluggish", "unhurried"],
    "kw:grow": ["grow", "grows", "growing", "expand", "expands", "expanding", "fill remaining", "take remaining space", "take up remaining space", "takes remaining space", "fills space", "fill space", "flex 1", "flex one", "takes up the rest", "fills the rest", "take the rest"],
    "kw:no-grow": ["no grow", "don't grow", "doesn't grow", "never grow", "fixed size", "not growing", "does not grow"],
    "kw:shrink": ["shrink", "shrinks", "shrinking", "can shrink", "allowed to shrink"],
    "kw:no-shrink": ["no shrink", "don't shrink", "doesn't shrink", "never shrink", "not shrinking", "keeps its size", "keep size", "does not shrink", "shrink 0", "won't shrink", "will not shrink", "prevent shrinking"],
    "kw:flex-none": ["flex none", "rigid", "inflexible", "neither grows nor shrinks", "no flex"],
    "kw:flex-auto": ["flex auto", "flexible auto", "grow and shrink", "grows and shrinks"],
    "kw:antialiased": ["antialiased", "anti aliased", "smoothed", "font smoothing", "smooth fonts", "crisp text", "anti-aliased"],
    "kw:blur": ["blurred", "blurry", "blur", "frosted", "frosted glass", "glassy", "glass effect", "out of focus", "fuzzy"],
    "kw:grayscale": ["grayscale", "greyscale", "black and white", "desaturated", "monochrome", "no color image", "b&w", "gray scale"],
    "kw:invisible": ["invisible", "visibility hidden", "hidden but keeps space", "hidden but takes space", "keeps its space", "transparent but present", "there but invisible", "not visible but present"],
    "kw:isolate": ["isolate", "isolated", "isolation", "new stacking context", "own stacking context"],
    "kw:group": ["group", "hover group", "parent group", "group parent", "as a group", "make it a group", "group container", "group wrapper"],
    "kw:peer": ["peer", "sibling peer", "as a peer", "make it a peer", "peer element"],
    "kw:aspect-auto": ["auto ratio", "natural ratio", "aspect auto", "original ratio", "intrinsic ratio"],
    "kw:reverse": ["reverse", "reversed", "backwards", "flipped order", "in reverse", "reverse order"],
    "kw:negative": ["negative", "minus", "pulled", "pull", "pulled up", "outdented", "negative margin"],
    "kw:mx-auto": ["auto margins", "margin auto", "margins auto", "auto horizontal margins", "centered with auto margins", "centered block", "horizontally centered block", "mx auto", "auto side margins", "auto margin", "centered horizontally with margin", "block centered"],
    "spec:center": ["centered", "centred", "center everything", "centre everything", "center content", "centre content", "centered content", "centred content", "content centered", "content centred", "center the content", "centre the content", "center the children", "centre the children", "centered children", "centred children", "in the middle", "dead center", "dead centre", "center aligned content", "centre aligned content", "center it", "centre it", "centered both ways", "centred both ways", "centered in both directions", "centred in both directions", "perfectly centered", "perfectly centred", "middle of the page", "center of the page", "centre of the page", "centered on the page", "centred on the page", "center everything inside", "centre everything inside", "fully centered", "fully centred", "everything centered", "everything centred", "items centered", "items centred", "center items", "centre items"],
    "spec:vcenter": ["vertically centered", "vertically centred", "centered vertically", "centred vertically", "middle aligned", "vertical center", "vertical centre", "vertically in the middle", "aligned to the middle", "align middle", "centered on the y axis", "centred on the y axis", "vertically aligned center", "vertically aligned centre", "vertically middle", "in the vertical middle", "aligned vertically in the center", "aligned vertically in the centre", "center vertically", "centre vertically"],
    "spec:hcenter": ["horizontally centered", "horizontally centred", "centered horizontally", "centred horizontally", "horizontal center", "horizontal centre", "centered on the x axis", "centred on the x axis", "horizontally aligned center", "horizontally aligned centre", "horizontally in the middle", "aligned horizontally in the center", "aligned horizontally in the centre", "center horizontally", "centre horizontally", "horizontally in the center", "horizontally in the centre"],
    "spec:fullscreen": ["full screen", "fullscreen", "whole screen", "entire screen", "whole viewport", "entire viewport", "full viewport", "fills the screen", "fill the screen", "cover the screen", "covers the whole screen", "full viewport size", "takes the whole screen", "takes the entire screen", "full-screen", "screen sized", "viewport sized", "fill the viewport", "fills the viewport"],
    "spec:cover-parent": ["fills the parent", "fill the parent", "cover the parent", "covers the parent", "stretched over the parent", "over the whole parent", "fill container", "fills the container", "fill the container", "covers the container", "cover its container", "cover the container", "fills its parent", "fill its parent", "stretch over parent", "stretched over parent", "positioned over the parent", "layered over the parent", "over the parent"],
    "spec:pin-top": ["pinned to the top", "stuck to the top", "at the very top", "pinned top", "top pinned", "anchored to the top", "anchored top", "glued to the top", "attached to the top", "flush with the top", "against the top", "along the top", "at the top edge", "pinned to top", "stuck to top", "fixed to the top", "on the top edge", "hugging the top"],
    "spec:pin-bottom": ["pinned to the bottom", "stuck to the bottom", "at the very bottom", "pinned bottom", "bottom pinned", "anchored to the bottom", "anchored bottom", "glued to the bottom", "attached to the bottom", "flush with the bottom", "against the bottom", "along the bottom", "at the bottom edge", "pinned to bottom", "stuck to bottom", "fixed to the bottom", "on the bottom edge", "hugging the bottom"],
    "spec:pin-left": ["pinned to the left", "stuck to the left", "at the far left", "pinned left", "left pinned", "anchored to the left", "anchored left", "glued to the left", "attached to the left", "flush with the left", "against the left", "along the left", "at the left edge", "pinned to left", "stuck to left", "on the left edge", "hugging the left", "on the left side", "left side"],
    "spec:pin-right": ["pinned to the right", "stuck to the right", "at the far right", "pinned right", "right pinned", "anchored to the right", "anchored right", "glued to the right", "attached to the right", "flush with the right", "against the right", "along the right", "at the right edge", "pinned to right", "stuck to right", "on the right edge", "hugging the right", "on the right side", "right side"],
    "spec:top-right": ["top right", "top-right", "in the top right", "upper right", "top right corner", "in the top right corner", "at the top right", "upper right corner", "northeast", "top right hand corner"],
    "spec:top-left": ["top left", "top-left", "in the top left", "upper left", "top left corner", "in the top left corner", "at the top left", "upper left corner", "northwest", "top left hand corner"],
    "spec:bottom-right": ["bottom right", "bottom-right", "in the bottom right", "lower right", "bottom right corner", "in the bottom right corner", "at the bottom right", "lower right corner", "southeast", "bottom right hand corner"],
    "spec:bottom-left": ["bottom left", "bottom-left", "in the bottom left", "lower left", "bottom left corner", "in the bottom left corner", "at the bottom left", "lower left corner", "southwest", "bottom left hand corner"],
    "spec:full-width": ["full width", "full-width", "fullwidth", "100% wide", "as wide as possible", "stretch across", "entire width", "whole width", "edge to edge", "full bleed", "spans the full width", "takes the full width", "the whole width", "complete width", "fills the width", "fill the width", "full horizontal", "max width available", "all the way across", "100% width", "wide as the parent", "as wide as the parent", "as wide as its parent", "the full width", "whole width of the parent", "stretches across", "stretch full width", "stretched full width"],
    "spec:full-height": ["full height", "full-height", "fullheight", "100% tall", "as tall as possible", "entire height", "whole height", "top to bottom height", "spans the full height", "takes the full height", "the whole height", "complete height", "fills the height", "fill the height", "full vertical", "100% height", "as tall as the parent", "as tall as its parent", "tall as the parent", "the full height", "stretch full height", "stretched full height"],
    "spec:flex-center": ["flex centered", "flex centred", "centered flex", "centred flex", "flex center", "flex centre"],
    "spec:sr-only": ["screen reader only", "screen readers only", "visually hidden", "sr only", "sr-only", "hidden visually", "accessible but hidden", "for screen readers", "only for screen readers", "hidden but accessible", "assistive only", "a11y hidden", "hidden except to screen readers", "read by screen readers only"],
}
