"""Natural-language property phrases -> property family key.

Family keys are the compiler's internal names (see src/compile.ts). The same
table is emitted into src/table.json so the TypeScript compiler and this
generator agree byte-for-byte.
"""

from __future__ import annotations

PROPS: dict[str, list[str]] = {
    # spacing
    "p": [
        "padding",
        "pad",
        "padded",
        "inner spacing",
        "inset spacing",
        "padding all around",
        "padding on all sides",
    ],
    "px": [
        "horizontal padding",
        "padding x",
        "px",
        "left and right padding",
        "padding left and right",
        "side padding",
    ],
    "py": [
        "vertical padding",
        "padding y",
        "py",
        "top and bottom padding",
        "padding top and bottom",
    ],
    "pt": ["top padding", "padding top", "padding on top", "pt"],
    "pr": ["right padding", "padding right", "padding on the right", "pr"],
    "pb": ["bottom padding", "padding bottom", "padding at the bottom", "pb"],
    "pl": ["left padding", "padding left", "padding on the left", "pl"],
    "m": [
        "margin",
        "margins",
        "outer spacing",
        "margin all around",
        "margin on all sides",
    ],
    "mx": [
        "horizontal margin",
        "margin x",
        "mx",
        "left and right margin",
        "side margins",
        "margin left and right",
    ],
    "my": [
        "vertical margin",
        "margin y",
        "my",
        "top and bottom margin",
        "margin top and bottom",
    ],
    "mt": [
        "top margin",
        "margin top",
        "margin on top",
        "mt",
        "space above",
        "spacing above",
    ],
    "mr": ["right margin", "margin right", "mr"],
    "mb": ["bottom margin", "margin bottom", "mb", "space below", "spacing below"],
    "ml": ["left margin", "margin left", "ml"],
    "gap": [
        "gap",
        "gaps",
        "spacing between",
        "space between items",
        "spacing between items",
        "gutter",
        "gap between",
    ],
    "gap-x": ["horizontal gap", "column gap", "gap x", "gap between columns"],
    "gap-y": ["vertical gap", "row gap", "gap y", "gap between rows"],
    "space-x": ["horizontal space between children", "space x"],
    "space-y": ["vertical space between children", "space y", "stack spacing"],
    # sizing
    "w": ["width", "wide", "w"],
    "h": ["height", "tall", "h", "high"],
    "size": ["size", "square size", "width and height"],
    "min-w": ["min width", "minimum width", "min w", "at least wide"],
    "max-w": [
        "max width",
        "maximum width",
        "max w",
        "at most wide",
        "capped width",
        "width capped at",
    ],
    "min-h": ["min height", "minimum height", "min h"],
    "max-h": ["max height", "maximum height", "max h", "capped height"],
    # typography
    "text": [
        "text",
        "font size",
        "text size",
        "type size",
        "font",
        "text color",
        "text colour",
        "font color",
        "font colour",
        "foreground",
        "foreground color",
        "color",
        "colour",
        "colored",
        "coloured",
        "typography",
        "copy",
        "label text",
        "the text",
        "text style",
        "font style",
        "lettering",
        "words",
        "wording",
        "the copy",
        "text content",
    ],
    "font": ["font weight", "weight", "text weight", "boldness"],
    "family": ["font family", "typeface", "font face"],
    "tracking": ["tracking", "letter spacing", "letterspacing", "character spacing"],
    "leading": ["leading", "line height", "lineheight", "line spacing"],
    "align": ["text align", "text alignment", "alignment", "aligned", "align"],
    "transform": ["text transform", "case", "text case", "letter case"],
    "decoration": ["text decoration", "decoration"],
    "wrap": ["text wrapping", "text wrap", "wrapping", "text overflow"],
    "whitespace": ["whitespace", "white space"],
    # colors and surfaces
    "bg": [
        "background",
        "bg",
        "background color",
        "background colour",
        "fill",
        "filled",
        "surface",
        "backdrop",
    ],
    "border": [
        "border",
        "borders",
        "outline border",
        "border color",
        "border colour",
        "stroke",
        "edge",
    ],
    "border-t": ["top border", "border top", "border on top", "border above"],
    "border-b": [
        "bottom border",
        "border bottom",
        "border at the bottom",
        "border below",
        "underline border",
    ],
    "border-l": ["left border", "border left", "border on the left"],
    "border-r": ["right border", "border right", "border on the right"],
    "border-x": [
        "horizontal borders",
        "left and right borders",
        "side borders",
        "border x",
    ],
    "border-y": ["vertical borders", "top and bottom borders", "border y"],
    "border-style": ["border style"],
    "rounded": [
        "rounded",
        "rounded corners",
        "corners",
        "corner radius",
        "border radius",
        "radius",
        "roundness",
        "rounding",
        "round corners",
        "curved corners",
        "rounded edges",
        "rounded off",
    ],
    "rounded-t": [
        "rounded top",
        "top corners rounded",
        "rounded top corners",
        "round the top",
    ],
    "rounded-b": [
        "rounded bottom",
        "bottom corners rounded",
        "rounded bottom corners",
        "round the bottom",
    ],
    "rounded-l": ["rounded left", "left corners rounded", "rounded left corners"],
    "rounded-r": ["rounded right", "right corners rounded", "rounded right corners"],
    "ring": ["ring", "focus ring", "outline ring", "halo"],
    "outline": ["outline"],
    "shadow": [
        "shadow",
        "drop shadow",
        "box shadow",
        "shadows",
        "elevation",
        "elevated",
        "shadowed",
    ],
    "opacity": [
        "opacity",
        "transparency",
        "alpha",
        "opaque",
        "see through",
        "translucent",
    ],
    # layout
    "display": ["display", "displayed as", "shown as"],
    "position": ["position", "positioned", "positioning"],
    "top": ["top offset", "from the top", "offset top", "distance from top", "top"],
    "bottom": [
        "bottom offset",
        "from the bottom",
        "offset bottom",
        "distance from bottom",
        "bottom",
    ],
    "left": ["left offset", "from the left", "offset left", "left"],
    "right": ["right offset", "from the right", "offset right", "right"],
    "inset": ["inset", "offset on all sides", "all offsets"],
    "z": ["z index", "z", "z-index", "stacking order", "layer", "stack order"],
    "overflow": [
        "overflow",
        "overflowing content",
        "content overflow",
        "scrolling",
        "scroll",
    ],
    "overflow-x": [
        "horizontal overflow",
        "overflow x",
        "horizontal scrolling",
        "horizontal scroll",
    ],
    "overflow-y": [
        "vertical overflow",
        "overflow y",
        "vertical scrolling",
        "vertical scroll",
    ],
    # flex / grid
    "flex": [
        "flex",
        "flexbox",
        "flex container",
        "flex layout",
        "flexible",
        "flex box",
    ],
    "direction": [
        "flex direction",
        "direction",
        "flow",
        "laid out",
        "layout direction",
        "stacked",
    ],
    "flexwrap": ["flex wrap", "item wrapping"],
    "grow": [
        "grow",
        "flex grow",
        "growing",
        "expand to fill",
        "fill remaining space",
        "fill available space",
        "stretch to fill",
    ],
    "shrink": ["shrink", "flex shrink", "shrinking"],
    "justify": [
        "justify",
        "justify content",
        "justified",
        "horizontal alignment",
        "main axis alignment",
        "horizontally aligned",
        "distribute",
        "distributed",
        "spread",
    ],
    "items": [
        "items",
        "align items",
        "vertical alignment",
        "cross axis alignment",
        "vertically aligned",
        "items aligned",
    ],
    "self": ["align self", "self aligned", "self"],
    "place": ["place items", "place content", "placed"],
    "grid": ["grid", "css grid", "grid layout", "grid container"],
    "cols": ["columns", "cols", "grid columns", "column grid", "column", "grid cols"],
    "rows": ["rows", "grid rows", "row grid"],
    "col-span": [
        "column span",
        "col span",
        "spans columns",
        "spanning columns",
        "span",
    ],
    "row-span": ["row span", "spans rows", "spanning rows"],
    "order": ["order", "ordered", "flex order"],
    # effects and interaction
    "transition": [
        "transition",
        "transitions",
        "transitioned",
        "animated transition",
        "smooth transition",
        "smoothly",
        "smooth",
        "eased",
    ],
    "duration": [
        "duration",
        "transition duration",
        "animation duration",
        "speed",
        "takes",
    ],
    "ease": ["easing", "timing function", "ease", "timing"],
    "delay": ["delay", "transition delay", "delayed by", "delayed"],
    "animate": ["animation", "animate", "animated", "animating"],
    "cursor": ["cursor", "mouse cursor", "pointer style", "mouse pointer"],
    "select": ["text selection", "selectable", "selection", "user select"],
    "pointer": ["pointer events", "mouse events", "clicks"],
    "object": ["object fit", "image fit", "fit", "image sizing", "fitted"],
    "aspect": ["aspect ratio", "aspect", "ratio", "proportions"],
    "scale": [
        "scale",
        "scaled",
        "zoom",
        "zoomed",
        "scaled up",
        "scaled down",
        "grows to",
        "size scale",
    ],
    "rotate": ["rotate", "rotated", "rotation", "turned", "tilted"],
    "blur": ["blur", "blurred", "blurry"],
    "list": ["list style", "list", "bullets", "list markers", "list type"],
    "visibility": ["visibility"],
    "columns": ["text columns", "column count", "multi column"],
    "lineclamp": [
        "line clamp",
        "clamp",
        "lines",
        "limited to",
        "max lines",
        "clamped to",
    ],
    "container": [
        "container",
        "page container",
        "content container",
        "wrapper",
        "max container",
    ],
    # presets (component nouns)
    "preset:card": ["card", "panel", "tile"],
    "preset:button": ["button", "btn", "cta", "call to action"],
    "preset:badge": ["badge", "chip", "tag", "label pill", "status badge"],
    "preset:avatar": ["avatar", "profile picture", "profile photo", "user photo"],
    "preset:input": [
        "input",
        "text input",
        "text field",
        "input field",
        "form field",
        "field",
    ],
    "preset:overlay": ["overlay", "backdrop overlay", "modal backdrop", "dim overlay"],
    "preset:divider": ["divider", "separator", "horizontal rule", "hr", "rule"],
    "preset:sr": [
        "screen reader only",
        "visually hidden",
        "sr only",
        "accessible only",
        "for screen readers",
    ],
}
