"""Writes ../src/lexicon.ts from lexicon.py so both sides share one keyword order.

    uv run python -m gpu_view.emit_lexicon
"""

from __future__ import annotations

import json
from pathlib import Path

from .lexicon import KEYWORDS, MONTH_ABBREV, MONTHS, POLARITY, SEASONS, UNITS

OUT = Path(__file__).resolve().parents[2] / "src" / "lexicon.ts"


def main() -> None:
    j = lambda v: json.dumps(v, ensure_ascii=False)  # noqa: E731
    lines = [
        "// Generated by training/gpu_view/emit_lexicon.py from lexicon.py. Do not edit by hand; the index is the feature id.",
        f"export const KEYWORDS: readonly string[] = {j(KEYWORDS)};",
        "export const KEYWORD_ID: ReadonlyMap<string, number> = new Map(KEYWORDS.map((w, i) => [w, i]));",
        "export const KEYWORD_COUNT = KEYWORDS.length;",
        f"export const MONTHS: readonly string[] = {j(MONTHS)};",
        f"export const MONTH_ABBREV: readonly string[] = {j(MONTH_ABBREV)};",
        '/** Adjective polarity: "high" superlatives sort descending and "X-er than" means gt. */',
        f'export const POLARITY: Readonly<Record<string, "high" | "low">> = {j(POLARITY)};',
        f"export const SEASONS: Readonly<Record<string, [number, number]>> = {j(SEASONS)};",
        f"export const UNITS: readonly string[] = {j(UNITS)};",
    ]
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT} ({len(KEYWORDS)} keywords)")


if __name__ == "__main__":
    main()
