import { describe, expect, it } from "vitest";
import {
  convTaggerForward,
  scanTaggerForward,
  type TaggerManifest,
  type TaggerModel,
  taggerForward,
} from "../src/models.ts";
import { decodeInt6 } from "../src/weights.ts";
import convFixture from "./fixtures/conv_tagger.json" with { type: "json" };
import scanFixture from "./fixtures/scan_tagger.json" with { type: "json" };

interface Fixture {
  manifest: TaggerManifest;
  weights: string;
  cases: { input: string; rows: number[][]; logits: number[][]; pooled: number[] | null }[];
}

function load(f: Fixture): TaggerModel {
  return { manifest: f.manifest, weights: decodeInt6(f.weights, f.manifest.tensors) };
}

function maxDiff(got: Float32Array, expected: number[]): number {
  expect(got.length).toBe(expected.length);
  let worst = 0;
  for (let i = 0; i < expected.length; i++)
    worst = Math.max(worst, Math.abs(got[i]! - expected[i]!));
  return worst;
}

/**
 * Fixtures are generated by `uv run python -m gpu_utils_training.fixtures` from random-weight
 * family models: the Python reference (on the decoded int6 weights) is the source of truth,
 * the canonical WGSL kernels are checked against the same files on lavapipe.
 */
describe.each([
  ["scan", scanFixture as unknown as Fixture, scanTaggerForward],
  ["conv", convFixture as unknown as Fixture, convTaggerForward],
])("%s tagger CPU forward", (family, fixture, forward) => {
  const model = load(fixture);
  it("has the expected family and at least 10 cases", () => {
    expect(model.manifest.family).toBe(family);
    expect(fixture.cases.length).toBeGreaterThanOrEqual(10);
  });
  it.each(fixture.cases.map((c, i) => [i, c.rows.length] as const))(
    "case %i (%i tokens) matches the Python reference at 1e-4",
    (i) => {
      const c = fixture.cases[i]!;
      const out = forward(model, c.rows);
      expect(maxDiff(out.tags, c.logits.flat())).toBeLessThan(1e-4);
      if (c.pooled) expect(maxDiff(out.pooled!, c.pooled)).toBeLessThan(1e-4);
      else expect(out.pooled).toBeUndefined();
    },
  );
  it("dispatches through taggerForward", () => {
    const c = fixture.cases[1]!;
    expect(Array.from(taggerForward(model, c.rows).tags)).toEqual(
      Array.from(forward(model, c.rows).tags),
    );
  });
  it("handles an empty sequence", () => {
    const out = forward(model, []);
    expect(out.tags.length).toBe(0);
  });
});
