"""Writes ../../src/keywords.ts from the constants in features.py so both featurizers
share one source of truth for keyword lists, slot layout and bucket edges.
`uv run python -m gpu_email.gen_keywords`."""

from __future__ import annotations

import json
from pathlib import Path

from gpu_email import features as f

OUT = Path(__file__).resolve().parents[2] / "src" / "keywords.ts"


def _arr(name: str, values: list) -> str:
    return f"export const {name} = {json.dumps(values, ensure_ascii=False)} as const;\n"


def main() -> None:
    lines = [
        "// GENERATED by training/gpu_email/gen_keywords.py from training/gpu_email/features.py.",
        "// Do not edit by hand; both featurizers must share these tables byte-for-byte.",
        "",
    ]
    for name in [
        "KW_WROTE",
        "KW_ORIGINAL",
        "KW_FORWARD",
        "KW_MOBILE",
        "KW_HEADER",
        "KW_DISCLAIMER",
        "KW_CONTACT_WORDS",
        "KW_CLOSING_WORDS",
        "KW_GREETING_WORDS",
        "KW_DATE_WORDS",
        "KW_CLOSING_PHRASES",
        "KW_GREETING_PHRASES",
        "EDGES_LINE_IDX",
        "EDGES_LINE_LEN",
        "EDGES_WORD_COUNT",
        "EDGES_DIGITS",
        "EDGES_SINCE_ATTRIB",
        "EDGES_PARA",
        "EDGES_PARA_POS",
        "EDGES_UNTIL_QUOTEISH",
        "EDGES_HEADER_RUN",
        "LINE_KINDS",
        "FIELDS",
        "BIO_LABELS",
    ]:
        lines.append(_arr(name, getattr(f, name)))
    lines.append(_arr("SLOTS", [[n, s] for n, s in f.SLOTS]))
    lines.append(_arr("SLOT_BASE", f.SLOT_BASE))
    lines.append(f"export const NUM_SLOTS = {f.NUM_SLOTS};\n")
    lines.append(f"export const NUM_ROWS = {f.NUM_ROWS};\n")
    lines.append(f"export const WORD_BUCKETS = {f.WORD_BUCKETS};\n")
    lines.append(f"export const SUFFIX_BUCKETS = {f.SUFFIX_BUCKETS};\n")
    lines.append(f"export const FIRST_WORD_BUCKETS = {f.FIRST_WORD_BUCKETS};\n")
    lines.append(f"export const LAST_WORD_BUCKETS = {f.LAST_WORD_BUCKETS};\n")
    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT} ({f.NUM_SLOTS} slots, {f.NUM_ROWS} rows)")


if __name__ == "__main__":
    main()
